# MODEL PARAMETERS

## PyTorch devices: "cpu", "cuda" or "cuda:{device_index}"
device: "cpu"

## Learning rate: https://en.wikipedia.org/wiki/Learning_rate
## In this implementation: a' = a - lr * gradient / num_samples,
## no additional manipulations to compute lr
lr: 0.2

## maximum number of iterations for model training
epochs: 1100

## Batch size: https://en.wikipedia.org/wiki/Stochastic_gradient_descent
## null - gradient descent: all values will be taken to calculate gradient
## 1 - stochastic gradient descent
## Other values are mini-batch or batch gradient descent
batch_size: null

## Random seed to reproduce results.
## seed >= 0
## null - means no random seed
seed: 42


# PREPROCESSING

## https://en.wikipedia.org/wiki/Feature_scaling
## "minmax" or "standard"
scale: "minmax"


## Features to train, predict or plot, look at data/dataset_*.csv
features:
    Arithmancy: False
    Astronomy: False
    Herbology: False
    Defense Against the Dark Arts: True
    Divination: True
    Muggle Studies: False
    Ancient Runes: True
    History of Magic: False
    Transfiguration: False
    Potions: False
    Care of Magical Creatures: False
    Charms: True
    Flying: True
